version: '3'
services:

  postgresDB:
    image: postgres:alpine
    container_name: trz_database
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=trz_database
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - trz-network
    restart: always

  app:
    build: .
    container_name: trz_app
    ports:
      - 3333:3333
    networks:
      - trz-network
    depends_on:
      - "postgresDB"
    restart: always

volumes:
  db_data: ./data

networks:
  trz-network:
    driver: bridge
